events {
    worker_connections 1024;
}

http {
    server_tokens off;
    gzip on;
    gzip_types text/plain application/json;
    
    log_format detailed '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        'rt=$request_time';

    access_log /var/log/nginx/access.log detailed;
    error_log  /var/log/nginx/error.log warn;
    upstream app {
        server app:5000;
    }

    # HTTP → HTTPS Redirect
    server {
        listen 80;
        server_name devops.local;
        
        return 301 https://$host$request_uri;
    }

    # HTTPS Server
    server {
        listen 443 ssl;
        server_name devops.local;

        # الشهادات
        ssl_certificate     /etc/nginx/certs/devops.local.crt;
        ssl_certificate_key /etc/nginx/certs/devops.local.key;

        # إعدادات SSL آمنة
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        # Security Headers
        add_header Strict-Transport-Security "max-age=31536000" always;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";

        location / {
            proxy_pass http://app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /health {
            proxy_pass http://app/health;
            access_log off;
        }
# Grafana
        location /grafana/ {
            proxy_pass http://grafana:3000/grafana/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Prometheus (محمي - شبكة داخلية فقط)
        location /prometheus/ {
            proxy_pass http://prometheus:9090/;
            proxy_set_header Host $host;
            allow 192.168.251.0/24;
            deny all;
        }
    }
}
